language: python
python:
    - 3.5

install:
    - pip install --upgrade pipenv
    - pipenv install --three --dev
    - pipenv uninstall django 
    - pipenv install django==1.8.18; django=<1.11

script:
    - pipenv run pytest

